# Custom Language File for Launcher Customizer

[ejs.app]
title = "KTZ Launcher"

[ejs.landing]
mediaHomeURL = "https://github.com/Katozarasi/KTZ-Launcher"
mediaLinkURL = "#"
mediaMapURL = "#"
mediaGitHubURL = "https://github.com/Katozarasi/KTZ-Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/Katozarasi/KTZ-Launcher"
supportLink = "https://github.com/Katozarasi/KTZ-Launcher/issues"

[ejs.welcome]
welcomeHeader = "KTZ Launcher"
welcomeDescription = "KTZ Launcher는 여러 Minecraft 서버의 버전과 모드 구성을 자동으로 관리하고, 원하는 서버를 골라 바로 접속할 수 있도록 도와드려요."
welcomeDescCTA = "서버를 선택하고 새로운 모험을 시작해 보세요!"
